# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'jobcore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jobcore
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'GoogleAppMeasurement', '~> 5.2.0'  

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'jobcoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'jobcore-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jobcore-tvOS

  target 'jobcore-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
