# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'coJobcoreTalent' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jobcore
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'GoogleAppMeasurement', '~> 5.2.0'

  # Add new pods below this line
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)

      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end

      if targets_to_ignore.include? target.name
        target.remove_from_project
      end

      if target.name == "React"
        target.remove_from_project
      end

    end
  end

end
